Fatal error: exception Failure("Continue can only be used within a loop")
